import type { Metadata } from "next";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";

// Define font-face rules in a global CSS file
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Link to local font files */}
        <style>{`
          @font-face {
            font-family: 'Geist';
            src: url('/fonts/Geist.woff2') format('woff2'),
                 url('/fonts/Geist.woff') format('woff');
            font-weight: 100 900;
            font-display: swap;
          }

          @font-face {
            font-family: 'Geist Mono';
            src: url('/fonts/GeistMono.woff2') format('woff2'),
                 url('/fonts/GeistMono.woff') format('woff');
            font-weight: 100 900;
            font-display: swap;
          }

          :root {
            --font-geist-sans: 'Geist', sans-serif;
            --font-geist-mono: 'Geist Mono', monospace;
          }
        `}</style>
      </head>
      <body
        className="antialiased"
        style={{
          fontFamily: `var(--font-geist-sans), var(--font-geist-mono)`,
        }}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
